### ISSUE TITLE
[Proposal] Consider adding REPL command history 

### ISSUE THREAD

**Issue by d-dizhevsky** [terrajobst/minsk#27]
It would be handy if we could use Up/Down buttons to walk through the history 

This package seems to be working (AFAIK @filip_woj has used it for `dotnet-script`).

Also this sounds like a good `up-for-grabs` feature :)

**Comment by terrajobst** [comment]
Great idea!

Did you mean to link to a specific NuGet package?

**Comment by d-dizhevsky** [comment]
@terrajobst yeah sorry, 

this is the package: https://www.nuget.org/packages/ReadLine/
and this is the PR from @filip_woj which we could use as a reference https://github.com/filipw/dotnet-script/pull/394

**Comment by terrajobst** [comment]
I see. I think I like the idea, but I'd rather not depend on a NuGet package. This seems like the kind of functionality that's easy enough to have here. I might be wrong, but that's my gut feel.

**Comment by terrajobst** [comment]
On second thought, in order to intercept the keys we can no longer use `Console.ReadLine()` which now means we'd need to handle all key processing (left right, selection, jumping between words, clearing line, editing the text, rendering it to the screen etc). That would be a lot of code; so taking a dependency on this package seems justified :-)

**Comment by terrajobst** [comment]
This was resolved in #40 :-)
