### ISSUE TITLE
Exception when evaluating token sequences <ArbitraryToken> <IdentifierToken>

### ISSUE THREAD

**Issue by peterwurzinger** [terrajobst/minsk#30]
Currently there is a problem with matching the following expected token sequence:
`[ArbitraryToken] <IdentifierToken>`

In case of valid inputs, this works like a charm. But think of malformed inputs like:
`for while` - _while_ is a keyword, not an identifier
`var 1` - _1_ is a number, not an identifier
`while let` - _let_ is a keyword, not an identifier
...
When an expected token of kind `IdentifierToken` cannot be matched (see above) the parser inserts one with`{Kind = SyntaxKind.Identifier, Text = null, Value = null}` and reports an unexpected token - diagnostic.

The parser diagnostics don't get reported immediately but concatenated with the diagnostics from the binder - what implies binding the (malformed) syntax tree first. And when it comes to binding, those inserted tokens start to hurt:
The most of the parsed identifier tokens are bound to `VariableSymbols` with `SyntaxToken.Text` as variable name. And when trying to declare it in its scope this ultimately leads to either
`_variables.ContainsKey(null)`
or
`_variables.Add(null, variable)`

Dictionaries don't like nulls, so both calls lead to an ArgumentNullException.

I decided to not file a PR, because there are various ways of fixing that issue and I don't know which one you would prefer.

/Peter

EDIT: Tried to clarify the problem.

**Comment by terrajobst** [comment]
This is a good one.

The general philosophy is that the binder needs to be able to work on any trees. Otherwise, it's basically impossible to develop something like an IDE where semantic questions need to be answered all the time.

In my [next live stream](https://www.youtube.com/watch?v=VkFNanrdvLc) I'm going to introduce a type symbols, which includes an error type. This will allow us to not cascade errors. Your particular issue has an easy fix though: we shouldn't be declaring variables. I'll fix that during the next compiler stream.

**Comment by peterwurzinger** [comment]
New episodes getting announced on my birthday. Best. Day. Ever. :tada:

**Comment by terrajobst** [comment]
![](https://media.giphy.com/media/xTiTnMhJTwNHChdTZS/giphy.gif)
