### ISSUE TITLE
[Question]FunctionSymbol references syntax

### ISSUE THREAD

**Issue by LunicLynx** [terrajobst/minsk#88]
Hello,

I'm currently trying to make the mental separation between parsing an binding.

And everything makes sense so far. Parsing is the step to make sense of the syntax, while binding is the step to make sense of the semantics.
And this distinctions works in `Minsk` with all bound types and symbols, except `FunctionSymbol`.

`FunctionSymbol` has a reference to the declaration syntax. 

My question is now: Is this on purpose or is it just something that wasn't addressed yet?

If it is on purpose, what is the benefit?
As far as i can see, the syntax, should not be relevant after successful binding.

Edit: Fix spelling, Markdown

**Comment by terrajobst** [comment]
Hey @LunicLynx,

You can see the references to FunctionSymbol.Declaration [here](http://source.minsk-compiler.net/#Minsk/CodeAnalysis/Symbols/FunctionSymbol.cs,ce42b1dd707c05df,references).

> `FunctionSymbol` has a reference to the declaration syntax.
> 
> My question is now: Is this on purpose or is it just something that wasn't addressed yet?

That's a good question. We could probably replace the `Declaration` property with a reference to the location because most usages seem to be related to error handling and in the other places it seems we would have access to the syntax.

But I'm not sure this will work for all cases. Syntax is independent, meaning each file can be parsed independently. Semantics are more complex because our language doesn't do forward declarations (IOW, you don't have to declare a function before you can call, we'll just find the definitions). The way this is being done in most compiler is that binding is done in phases. In Minsk, we have basically two steps:

1. Binding all function signatures (we call this the `BoundGlobalScope`)
2. Binding of each function body (we call this the `BoundProgram`)

Once step (1) is concluded, we can bind each function body independently (and if we wanted to even in parallel). It's a bit easier for us to this if the symbols have references to their syntax nodes, but that's not strictly speaking necessary.

Also, if we think of the compiler APIs as a library, it's useful for consumers if symbols have a reference to their syntax nodes, but we currently don't do this consistently (for example, a `LocalVariableSymbol` doesn't do that).

Does this make sense?

**Comment by LunicLynx** [comment]
Hi @terrajobst,

thanks for the extensive answer.

Yes, that helped a lot. I'm really interested to see how this project develops in the future. 
Will you cover OOP like constructs at some point?

Please keep going!

**Comment by terrajobst** [comment]
> Will you cover OOP like constructs at some point?

Maybe, we'll see how this goes :-)
